packages:
  - "*"

catalog:
  "@clusterio/lib": ^2.0.0-alpha.21
  "@clusterio/web_ui": ^2.0.0-alpha.21
  "@sinclair/typebox": ^0.34.39
  "discord.js": ^14.21.0
  "webpack": ^5.101.2
  "webpack-cli": ^6.0.1
  "webpack-merge": ^6.0.1
